import "server-only";
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import type { StorageProvider, StoredFile, ReadFileResult } from "@/lib/storage/provider";
import { signResourceAccess } from "@/lib/storage/signed-url";

/**
 * Dev implementation of StorageProvider — writes to the gitignored `.data/`
 * directory (see .gitignore: "local media storage (dev adapter)" /
 * `/.data`, and `STORAGE_LOCAL_PATH` in .env.example, already reserved for
 * this since the Phase 2 placeholder-URL era). No production
 * Supabase/S3 adapter is built — that stays unselected per INTEGRATIONS.md,
 * exactly like the facial-verification and telematics vendors; swapping one
 * in later means implementing this same StorageProvider interface, not
 * changing any call site.
 *
 * Files are served back only through `/api/media/[id]` (mints a signed URL
 * after a permission check) → `/api/media/raw` (verifies the signature
 * server-side, then streams bytes). Next.js never serves `.data/` as a
 * static path — there is no public/permanent URL to this content at all.
 */
export class LocalFilesystemStorageProvider implements StorageProvider {
  private readonly baseDir: string;
  private readonly signedUrlBasePath = "/api/media/raw";

  constructor(baseDir: string = process.env.STORAGE_LOCAL_PATH || "./.data/media") {
    // turbopackIgnore: this is plain runtime path resolution against a fixed
    // env-configured directory, not a dynamic require/bundling concern — see
    // the Turbopack NFT warning this silences.
    this.baseDir = path.resolve(/* turbopackIgnore: true */ process.cwd(), baseDir);
  }

  private resolvePath(storageKey: string): string {
    // storageKey is always generated by this class (tenantId/uuid-filename,
    // both cuid/uuid-derived segments) — never taken verbatim from client
    // input — but normalize defensively so a malformed key can never escape
    // baseDir via `..` traversal.
    const resolved = path.resolve(this.baseDir, storageKey);
    if (!resolved.startsWith(this.baseDir + path.sep) && resolved !== this.baseDir) {
      throw new Error("Refusing to resolve a storage key outside the storage root.");
    }
    return resolved;
  }

  async store(tenantId: string, fileName: string, data: Buffer, contentType: string): Promise<StoredFile> {
    const safeName = fileName.replace(/[^a-zA-Z0-9._-]/g, "_").slice(-100);
    const storageKey = `${tenantId}/${crypto.randomUUID()}-${safeName}`;
    const fullPath = this.resolvePath(storageKey);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, data);
    // Sidecar metadata file so read() can recover the content-type without a
    // DB round trip — MediaAsset.contentType remains the authoritative copy
    // used everywhere else; this is purely so the local dev adapter is
    // self-contained.
    await fs.writeFile(`${fullPath}.meta.json`, JSON.stringify({ contentType }), "utf8");

    const checksumSha256 = crypto.createHash("sha256").update(data).digest("hex");
    return { storageKey, checksumSha256 };
  }

  async getSignedReadUrl(storageKey: string, expiresInSeconds: number): Promise<string> {
    const token = signResourceAccess(storageKey, expiresInSeconds);
    const encodedKey = Buffer.from(storageKey, "utf8").toString("base64url");
    return `${this.signedUrlBasePath}?key=${encodedKey}&expires=${token.expiresAt}&sig=${token.signature}`;
  }

  async read(storageKey: string): Promise<ReadFileResult | null> {
    try {
      const fullPath = this.resolvePath(storageKey);
      const [data, metaRaw] = await Promise.all([
        fs.readFile(fullPath),
        fs.readFile(`${fullPath}.meta.json`, "utf8").catch(() => '{"contentType":"application/octet-stream"}'),
      ]);
      const meta = JSON.parse(metaRaw) as { contentType?: string };
      return { data, contentType: meta.contentType ?? "application/octet-stream" };
    } catch (err) {
      if ((err as NodeJS.ErrnoException)?.code === "ENOENT") return null;
      throw err;
    }
  }

  async delete(storageKey: string): Promise<void> {
    const fullPath = this.resolvePath(storageKey);
    await fs.rm(fullPath, { force: true });
    await fs.rm(`${fullPath}.meta.json`, { force: true });
  }
}
