import "server-only";
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import type { ObjectStorageProvider, StoredFile, ReadFileResult, PresignedUpload, ConfirmUploadResult, StorageProviderCapabilities, StorageHealthResult } from "@/lib/storage/provider";
import { signResourceAccess } from "@/lib/storage/signed-url";
import type { MediaCategory } from "@/generated/prisma/client";

/**
 * Dev implementation of ObjectStorageProvider — writes to the gitignored
 * `.data/` directory (see .gitignore: "local media storage (dev adapter)" /
 * `/.data`, and `STORAGE_LOCAL_PATH` in .env.example, already reserved for
 * this since the Phase 2 placeholder-URL era). No production Supabase/S3/R2
 * adapter is selected here — that stays unselected per INTEGRATIONS.md,
 * exactly like the facial-verification and telematics vendors; swapping one
 * in later means implementing this same ObjectStorageProvider interface, not
 * changing any call site. See `r2-compatible-provider.ts` for the
 * provider-neutral configuration boundary for when a real account exists.
 *
 * Files are served back only through `/api/media/[id]` (mints a signed URL
 * after a permission check) → `/api/media/raw` (verifies the signature
 * server-side, then streams bytes). Next.js never serves `.data/` as a
 * static path — there is no public/permanent URL to this content at all.
 *
 * Presigned upload (Phase 8B): since there is no real object-storage vendor
 * to hand a presigned PUT to in local dev, `createPresignedUpload()` mints
 * an HMAC-signed *upload*-purpose token (distinct from a read token — see
 * signed-url.ts's `purpose` parameter) pointing at
 * `PUT /api/media/raw-upload`, which verifies the signature/expiry/purpose
 * before writing the request body straight to the reserved storage key —
 * the same "direct-to-storage, server verifies after the fact" shape a real
 * S3/R2 presigned URL has, just self-hosted.
 */
export class LocalFilesystemStorageProvider implements ObjectStorageProvider {
  readonly providerId = "local";
  readonly capabilities: StorageProviderCapabilities = {
    privateObjects: true,
    tenantPrefixedKeys: true,
    signedReads: true,
    presignedUploads: true,
    integrityMetadata: true,
    deleteObjects: true,
    archiveTier: false,
    legalHoldApi: false,
    credentialRotation: true,
  };
  private readonly baseDir: string;
  private readonly signedReadBasePath = "/api/media/raw";
  private readonly signedUploadBasePath = "/api/media/raw-upload";

  constructor(baseDir: string = process.env.STORAGE_LOCAL_PATH || "./.data/media") {
    // turbopackIgnore: this is plain runtime path resolution against a fixed
    // env-configured directory, not a dynamic require/bundling concern — see
    // the Turbopack NFT warning this silences.
    this.baseDir = path.resolve(/* turbopackIgnore: true */ process.cwd(), baseDir);
  }

  async healthCheck(): Promise<StorageHealthResult> {
    try {
      await fs.mkdir(this.baseDir, { recursive: true });
      await fs.access(this.baseDir);
      return { status: "healthy", detail: "local private storage is writable" };
    } catch {
      return { status: "degraded", detail: "local private storage is unavailable" };
    }
  }

  private resolvePath(storageKey: string): string {
    // storageKey is always generated by this class (tenantId/category/uuid-filename
    // segments) — never taken verbatim from client input — but normalize
    // defensively so a malformed key can never escape baseDir via `..` traversal.
    const resolved = path.resolve(this.baseDir, storageKey);
    if (!resolved.startsWith(this.baseDir + path.sep) && resolved !== this.baseDir) {
      throw new Error("Refusing to resolve a storage key outside the storage root.");
    }
    return resolved;
  }

  private buildStorageKey(tenantId: string, category: MediaCategory, fileName: string): string {
    const safeName = fileName.replace(/[^a-zA-Z0-9._-]/g, "_").slice(-100);
    return `${tenantId}/${category}/${crypto.randomUUID()}-${safeName}`;
  }

  async store(tenantId: string, category: MediaCategory, fileName: string, data: Buffer, contentType: string): Promise<StoredFile> {
    const storageKey = this.buildStorageKey(tenantId, category, fileName);
    await this.writeObject(storageKey, data, contentType);
    const checksumSha256 = crypto.createHash("sha256").update(data).digest("hex");
    return { storageKey, checksumSha256, fileSizeBytes: data.byteLength };
  }

  /** Shared by `store()` and the `/api/media/raw-upload` route handler (which resolves its own path via this same class). */
  async writeObject(storageKey: string, data: Buffer, contentType: string): Promise<void> {
    const fullPath = this.resolvePath(storageKey);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, data);
    // Sidecar metadata file so read() can recover the content-type without a
    // DB round trip — MediaAsset.contentType remains the authoritative copy
    // used everywhere else; this is purely so the local dev adapter is
    // self-contained.
    await fs.writeFile(`${fullPath}.meta.json`, JSON.stringify({ contentType }), "utf8");
  }

  async createPresignedUpload(
    tenantId: string,
    category: MediaCategory,
    fileName: string,
    contentType: string,
    expiresInSeconds: number,
  ): Promise<PresignedUpload> {
    const storageKey = this.buildStorageKey(tenantId, category, fileName);
    const token = signResourceAccess(storageKey, expiresInSeconds, "upload");
    const encodedKey = Buffer.from(storageKey, "utf8").toString("base64url");
    return {
      uploadUrl: `${this.signedUploadBasePath}?key=${encodedKey}&expires=${token.expiresAt}&sig=${token.signature}`,
      method: "PUT",
      headers: { "Content-Type": contentType },
      storageKey,
      expiresAt: token.expiresAt,
    };
  }

  async confirmUpload(storageKey: string): Promise<ConfirmUploadResult> {
    try {
      const stat = await fs.stat(this.resolvePath(storageKey));
      return { exists: true, fileSizeBytes: stat.size };
    } catch (err) {
      if ((err as NodeJS.ErrnoException)?.code === "ENOENT") return { exists: false, fileSizeBytes: null };
      throw err;
    }
  }

  async getSignedReadUrl(storageKey: string, expiresInSeconds: number): Promise<string> {
    const token = signResourceAccess(storageKey, expiresInSeconds, "read");
    const encodedKey = Buffer.from(storageKey, "utf8").toString("base64url");
    return `${this.signedReadBasePath}?key=${encodedKey}&expires=${token.expiresAt}&sig=${token.signature}`;
  }

  async read(storageKey: string): Promise<ReadFileResult | null> {
    try {
      const fullPath = this.resolvePath(storageKey);
      const [data, metaRaw] = await Promise.all([
        fs.readFile(fullPath),
        fs.readFile(`${fullPath}.meta.json`, "utf8").catch(() => '{"contentType":"application/octet-stream"}'),
      ]);
      const meta = JSON.parse(metaRaw) as { contentType?: string };
      return { data, contentType: meta.contentType ?? "application/octet-stream" };
    } catch (err) {
      if ((err as NodeJS.ErrnoException)?.code === "ENOENT") return null;
      throw err;
    }
  }

  async delete(storageKey: string): Promise<void> {
    const fullPath = this.resolvePath(storageKey);
    await fs.rm(fullPath, { force: true });
    await fs.rm(`${fullPath}.meta.json`, { force: true });
  }
}
