"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const STEPS = ["Company", "Fleet plan", "Sites & gates", "Vehicles", "Drivers", "Staff", "Assignments", "Review"] as const;
const SECTION_KEYS = ["company", "fleet", "sites", "vehicles", "drivers", "staff", "assignments", "review"] as const;
const CATEGORIES = ["TRUCK", "BAKKIE_PICKUP", "VAN", "PASSENGER", "SALES_REPRESENTATIVE", "TRAILER", "PLANT_EQUIPMENT", "OTHER"] as const;
type Summary = { tenant: { name: string; companyRegistrationNumber: string | null; industry: string | null; contactEmail: string | null; contactPhone: string | null; address: string | null; departments: string[] }; onboarding: { currentStep: number; completedSections: string[]; declaredFleetSize: number | null; fleetComposition: Record<string, number> | null; completedAt: string | null }; counts: Record<string, number>; readiness: Record<string, boolean> };
type Option = { id: string; name?: string; registrationNumber?: string; employeeNumber?: string | null };

export function OnboardingWizard() {
  const router = useRouter();
  const [summary, setSummary] = useState<Summary | null>(null);
  const [step, setStep] = useState(1);
  const [sites, setSites] = useState<Array<Option & { gates: Option[] }>>([]);
  const [drivers, setDrivers] = useState<Option[]>([]);
  const [vehicles, setVehicles] = useState<Option[]>([]);
  const [roles, setRoles] = useState<Option[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [inviteLink, setInviteLink] = useState<string | null>(null);

  const load = useCallback(async () => {
    const [onboardingResponse, sitesResponse, driversResponse, vehiclesResponse, rolesResponse] = await Promise.all([
      fetch("/api/onboarding"), fetch("/api/admin/sites"), fetch("/api/drivers?pageSize=100"), fetch("/api/vehicles?pageSize=100"), fetch("/api/admin/roles"),
    ]);
    const onboarding = await onboardingResponse.json();
    if (!onboardingResponse.ok) throw new Error(onboarding.error ?? "Onboarding could not be loaded");
    setSummary(onboarding);
    setStep((current) => current === 1 ? onboarding.onboarding.currentStep : current);
    if (sitesResponse.ok) setSites((await sitesResponse.json()).sites);
    if (driversResponse.ok) setDrivers((await driversResponse.json()).items);
    if (vehiclesResponse.ok) setVehicles((await vehiclesResponse.json()).items);
    if (rolesResponse.ok) setRoles((await rolesResponse.json()).roles);
  }, []);

  useEffect(() => { queueMicrotask(() => load().catch((cause) => setError(cause.message))); }, [load]);

  async function request(url: string, method: string, body: unknown) {
    setBusy(true); setError(null); setMessage(null);
    try {
      const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error ?? "The change could not be saved");
      return result;
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "The change could not be saved");
      return null;
    } finally { setBusy(false); }
  }

  async function saveStep(completed: boolean) {
    if (!summary) return;
    const next = Math.min(8, step + 1);
    const completedSections = completed ? [...new Set([...summary.onboarding.completedSections, SECTION_KEYS[step - 1]])] : summary.onboarding.completedSections;
    const result = await request("/api/onboarding", "PATCH", { currentStep: next, completedSections });
    if (result) { setSummary(result); setStep(next); setMessage("Progress saved."); }
  }

  async function formRequest(event: React.FormEvent<HTMLFormElement>, url: string, map: (form: FormData) => unknown, success: string) {
    event.preventDefault();
    const formElement = event.currentTarget;
    const result = await request(url, "POST", map(new FormData(formElement)));
    if (result) { formElement.reset(); setMessage(success); await load(); }
    return result;
  }

  if (!summary) return <div role="status" className="rounded-2xl bg-white p-8 text-sm text-slate-600">Loading saved onboarding progress…</div>;
  const field = "mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-cyan-700 focus:ring-2 focus:ring-cyan-100";
  const completion = Object.values(summary.readiness).filter(Boolean).length;

  return <div className="grid gap-6 lg:grid-cols-[260px_1fr]">
    <aside className="rounded-3xl bg-slate-950 p-5 text-white lg:sticky lg:top-6 lg:self-start">
      <p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Onboarding progress</p>
      <p className="mt-3 text-3xl font-semibold">{completion}/7 ready</p>
      <ol className="mt-6 space-y-1" aria-label="Onboarding steps">{STEPS.map((name, index) => { const number = index + 1; const done = summary.onboarding.completedSections.includes(SECTION_KEYS[index]); return <li key={name}><button type="button" onClick={() => setStep(number)} aria-current={step === number ? "step" : undefined} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left text-sm ${step === number ? "bg-white text-slate-950" : "text-slate-300 hover:bg-white/10"}`}><span aria-hidden="true" className={`flex size-6 items-center justify-center rounded-full text-xs ${done ? "bg-emerald-400 text-slate-950" : "border border-current"}`}>{done ? "✓" : number}</span>{name}</button></li>; })}</ol>
      <Link href="/dashboard" className="mt-6 block rounded-xl border border-white/20 px-3 py-2 text-center text-sm hover:bg-white/10">Preview dashboard</Link>
    </aside>

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8">
      <div className="mb-6"><p className="text-xs font-semibold uppercase tracking-wide text-cyan-800">Step {step} of 8</p><h1 className="mt-1 text-2xl font-semibold text-slate-950">{STEPS[step - 1]}</h1><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-cyan-600" style={{ width: `${step / 8 * 100}%` }} /></div></div>
      {error && <p role="alert" aria-live="assertive" className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}
      {message && <p role="status" aria-live="polite" className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}

      {step === 1 && <form onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await request("/api/onboarding", "PATCH", { company: { name: form.get("name"), companyRegistrationNumber: form.get("registration") || null, industry: form.get("industry") || null, contactEmail: form.get("email") || null, contactPhone: form.get("phone") || null, address: form.get("address") || null, departments: String(form.get("departments") ?? "").split(",").map((v) => v.trim()).filter(Boolean) }, currentStep: 2, completedSections: [...new Set([...summary.onboarding.completedSections, "company"])] }); if (result) { setSummary(result); setStep(2); } }} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Company name<input name="name" required defaultValue={summary.tenant.name} className={field} /></label><label className="text-sm font-medium">Industry<input name="industry" required defaultValue={summary.tenant.industry ?? ""} className={field} /></label><label className="text-sm font-medium">Registration number<input name="registration" defaultValue={summary.tenant.companyRegistrationNumber ?? ""} className={field} /></label><label className="text-sm font-medium">Company email<input name="email" type="email" defaultValue={summary.tenant.contactEmail ?? ""} className={field} /></label><label className="text-sm font-medium">Company phone<input name="phone" defaultValue={summary.tenant.contactPhone ?? ""} className={field} /></label><label className="text-sm font-medium">Departments, comma separated<input name="departments" defaultValue={summary.tenant.departments.join(", ")} className={field} /></label><label className="text-sm font-medium sm:col-span-2">Address<textarea name="address" rows={3} defaultValue={summary.tenant.address ?? ""} className={field} /></label><button disabled={busy} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white sm:col-span-2">Save company and continue</button></form>}

      {step === 2 && <form onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const composition = Object.fromEntries(CATEGORIES.map((category) => [category, Number(form.get(category) ?? 0)])); const declaredFleetSize = Object.values(composition).reduce((sum, value) => sum + value, 0); const result = await request("/api/onboarding", "PATCH", { fleet: { declaredFleetSize, fleetComposition: composition }, currentStep: 3, completedSections: [...new Set([...summary.onboarding.completedSections, "fleet"])] }); if (result) { setSummary(result); setStep(3); } }}><p className="mb-4 text-sm text-slate-600">Enter the expected number in each category. The declared total is calculated and reconciled with loaded vehicles.</p><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{CATEGORIES.map((category) => <label key={category} className="text-sm font-medium">{category.replaceAll("_", " ")}<input name={category} type="number" min="0" max="100000" defaultValue={summary.onboarding.fleetComposition?.[category] ?? 0} className={field} /></label>)}</div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><strong>{summary.onboarding.declaredFleetSize ?? 0}</strong> declared · <strong>{summary.counts.loadedVehicles}</strong> vehicles loaded · <strong>{summary.counts.outstandingVehicles}</strong> outstanding against saved plan</div><button disabled={busy} className="mt-4 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Save fleet plan and continue</button></form>}

      {step === 3 && <div className="space-y-6"><form onSubmit={(event) => formRequest(event, "/api/admin/sites", (form) => ({ name: form.get("name"), address: form.get("address") || undefined }), "Site added.")} className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-medium">Site name<input name="name" required className={field} /></label><label className="text-sm font-medium">Address<input name="address" className={field} /></label><button disabled={busy} className="self-end rounded-xl bg-slate-950 px-3 py-2.5 text-sm font-semibold text-white">Add site</button></form>{sites.length > 0 && <form onSubmit={(event) => formRequest(event, "/api/admin/gates", (form) => ({ siteId: form.get("siteId"), name: form.get("name"), direction: form.get("direction") }), "Gate added.")} className="grid gap-3 sm:grid-cols-4"><label className="text-sm font-medium">Site<select name="siteId" className={field}>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label className="text-sm font-medium">Gate name<input name="name" required className={field} /></label><label className="text-sm font-medium">Direction<select name="direction" className={field}><option>BOTH</option><option>ENTRY</option><option>EXIT</option></select></label><button disabled={busy} className="self-end rounded-xl bg-slate-950 px-3 py-2.5 text-sm font-semibold text-white">Add gate</button></form>}<p className="text-sm text-slate-600">{summary.counts.sites} site(s) and {summary.counts.gates} gate(s) loaded.</p><button type="button" disabled={!summary.readiness.sites || busy} onClick={() => saveStep(true)} className="w-full rounded-xl bg-cyan-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue</button></div>}

      {step === 4 && <div><form onSubmit={(event) => formRequest(event, "/api/vehicles", (form) => ({ registrationNumber: form.get("registrationNumber"), fleetNumber: form.get("fleetNumber") || undefined, make: form.get("make") || undefined, model: form.get("model") || undefined, category: form.get("category"), carryingCapacityTonnes: form.get("carryingCapacityTonnes") || undefined, department: form.get("department") || undefined, fuelType: form.get("fuelType") || undefined, odometerReading: form.get("odometerReading") || undefined }), "Vehicle added.")} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Registration number<input name="registrationNumber" required className={field} /></label><label className="text-sm font-medium">Fleet / asset number<input name="fleetNumber" className={field} /></label><label className="text-sm font-medium">Category<select name="category" className={field}>{CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label className="text-sm font-medium">Carrying capacity (tonnes, required for trucks)<input name="carryingCapacityTonnes" type="number" min="0.1" step="0.1" className={field} /></label><label className="text-sm font-medium">Make<input name="make" className={field} /></label><label className="text-sm font-medium">Model<input name="model" className={field} /></label><label className="text-sm font-medium">Department / sales division<input name="department" className={field} /></label><label className="text-sm font-medium">Fuel type<select name="fuelType" className={field}><option value="">Not recorded</option><option>DIESEL</option><option>PETROL</option><option>ELECTRIC</option><option>HYBRID</option><option>OTHER</option></select></label><label className="text-sm font-medium">Current odometer<input name="odometerReading" type="number" min="0" className={field} /></label><button disabled={busy} className="self-end rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Add vehicle</button></form><p className="mt-4 text-sm text-slate-600">{summary.counts.loadedVehicles} loaded · {summary.counts.outstandingVehicles} outstanding. Richer fields, image and documents are available on each vehicle detail.</p><button type="button" disabled={!summary.readiness.vehicles || busy} onClick={() => saveStep(true)} className="mt-4 w-full rounded-xl bg-cyan-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue</button></div>}

      {step === 5 && <div><form onSubmit={(event) => formRequest(event, "/api/drivers", (form) => ({ name: form.get("name"), employeeNumber: form.get("employeeNumber") || undefined, contactPhone: form.get("contactPhone") || undefined, department: form.get("department") || undefined, licenceNumber: form.get("licenceNumber") || undefined, licenceClass: form.get("licenceClass") || undefined, licenceIssueDate: form.get("licenceIssueDate") || undefined, licenceExpiry: form.get("licenceExpiry") || undefined, pdpStatus: form.get("pdpStatus"), pdpNumber: form.get("pdpNumber") || undefined, pdpExpiry: form.get("pdpExpiry") || undefined }), "Driver added.")} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Name and surname<input name="name" required className={field} /></label><label className="text-sm font-medium">Employee number<input name="employeeNumber" className={field} /></label><label className="text-sm font-medium">Contact phone<input name="contactPhone" className={field} /></label><label className="text-sm font-medium">Department<input name="department" className={field} /></label><label className="text-sm font-medium">Licence number<input name="licenceNumber" className={field} /></label><label className="text-sm font-medium">Licence class<input name="licenceClass" className={field} /></label><label className="text-sm font-medium">Licence issue date<input name="licenceIssueDate" type="date" className={field} /></label><label className="text-sm font-medium">Licence expiry date<input name="licenceExpiry" type="date" className={field} /></label><label className="text-sm font-medium">Professional permit status<select name="pdpStatus" className={field}><option>NOT_REQUIRED</option><option>VALID</option><option>PENDING</option><option>EXPIRED</option><option>SUSPENDED</option></select></label><label className="text-sm font-medium">Professional permit number<input name="pdpNumber" className={field} /></label><label className="text-sm font-medium">Professional permit expiry<input name="pdpExpiry" type="date" className={field} /></label><button disabled={busy} className="self-end rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Add driver</button></form><p className="mt-4 text-sm text-slate-600">{summary.counts.drivers} driver(s) loaded. Add synthetic profile images and licence documents from driver details.</p><button type="button" disabled={!summary.readiness.drivers || busy} onClick={() => saveStep(true)} className="mt-4 w-full rounded-xl bg-cyan-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue</button></div>}

      {step === 6 && <div><form onSubmit={async (event) => { const result = await formRequest(event, "/api/admin/users/invite", (form) => ({ name: form.get("name"), email: form.get("email"), employeeNumber: form.get("employeeNumber") || undefined, roleId: form.get("roleId"), assignedSiteId: form.get("assignedSiteId") || undefined, assignedGateId: form.get("assignedGateId") || undefined }), "Staff access record created locally."); if (result?.invitationToken) setInviteLink(`${window.location.origin}/accept-invitation?token=${result.invitationToken}`); }} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Name<input name="name" required className={field} /></label><label className="text-sm font-medium">Employee number<input name="employeeNumber" className={field} /></label><label className="text-sm font-medium">Email<input name="email" type="email" required className={field} /></label><label className="text-sm font-medium">Role<select name="roleId" className={field}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><label className="text-sm font-medium">Assigned site<select name="assignedSiteId" className={field}><option value="">No site</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label className="text-sm font-medium">Assigned gate<select name="assignedGateId" className={field}><option value="">No gate</option>{sites.flatMap((site) => site.gates).map((gate) => <option key={gate.id} value={gate.id}>{gate.name}</option>)}</select></label><button disabled={busy} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white sm:col-span-2">Create local invitation</button></form>{inviteLink && <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><strong>No email was sent.</strong> Copy this one-time local invitation link: <span className="break-all">{inviteLink}</span></div>}<p className="mt-4 text-sm text-slate-600">Guards remain pending until a different authorised administrator or manager approves them on the staff screen.</p><div className="mt-4 flex gap-3"><Link href="/admin/users" className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold">Manage staff approvals</Link><button type="button" disabled={!summary.readiness.staff || busy} onClick={() => saveStep(true)} className="flex-1 rounded-xl bg-cyan-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue</button></div></div>}

      {step === 7 && <div><form onSubmit={(event) => formRequest(event, "/api/assignments", (form) => ({ driverId: form.get("driverId"), vehicleId: form.get("vehicleId"), reason: form.get("reason"), replaceExisting: form.get("replaceExisting") === "on" }), "Driver assigned; history preserved.")} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Driver<select name="driverId" className={field}>{drivers.map((driver) => <option key={driver.id} value={driver.id}>{driver.name}</option>)}</select></label><label className="text-sm font-medium">Vehicle<select name="vehicleId" className={field}>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.registrationNumber}</option>)}</select></label><label className="text-sm font-medium sm:col-span-2">Assignment reason<input name="reason" required minLength={5} placeholder="Initial synthetic fleet allocation" className={field} /></label><label className="flex items-start gap-2 text-sm sm:col-span-2"><input name="replaceExisting" type="checkbox" className="mt-1" /><span>End any conflicting active assignment and preserve it in history (reason must be at least 10 characters).</span></label><button disabled={busy || !drivers.length || !vehicles.length} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white sm:col-span-2">Assign driver</button></form><p className="mt-4 text-sm text-slate-600">{summary.counts.assignments} active assignment(s).</p><button type="button" disabled={!summary.readiness.assignments || busy} onClick={() => saveStep(true)} className="mt-4 w-full rounded-xl bg-cyan-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue</button></div>}

      {step === 8 && <div><div className="rounded-2xl bg-slate-50 p-5"><h2 className="font-semibold text-slate-950">Readiness summary</h2><ul className="mt-4 grid gap-2 sm:grid-cols-2">{Object.entries(summary.readiness).map(([key, ready]) => <li key={key} className={`rounded-xl border p-3 text-sm ${ready ? "border-emerald-200 bg-emerald-50 text-emerald-900" : "border-amber-200 bg-amber-50 text-amber-950"}`}><span aria-hidden="true">{ready ? "✓" : "!"}</span> {key.replaceAll("_", " ")} — {ready ? "ready" : "incomplete"}</li>)}</ul></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Synthetic demonstration boundaries:</strong> no live tracker is connected and no real personal, vehicle, location or biometric data may be used. <span className="font-bold">SYNTHETIC BIOMETRIC TEST — NOT REAL FACIAL VERIFICATION</span></div><button type="button" disabled={busy || completion < 7} onClick={async () => { const result = await request("/api/onboarding", "PATCH", { complete: true, completedSections: SECTION_KEYS }); if (result) { router.push("/dashboard"); router.refresh(); } }} className="mt-5 w-full rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Complete onboarding and launch dashboard</button></div>}

      <div className="mt-8 flex items-center justify-between border-t border-slate-100 pt-4"><button type="button" disabled={step === 1} onClick={() => setStep((value) => Math.max(1, value - 1))} className="rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:opacity-40">Previous</button><button type="button" onClick={() => saveStep(false)} disabled={busy} className="text-sm font-medium text-slate-600 hover:underline">Save and continue later</button></div>
    </section>
  </div>;
}
