"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Rule = { id: string; code: string; label: string; description: string; version: number; enabled: boolean; evaluationPeriodDays: number; minimumOccurrenceCount: number; severity: string; percentageThreshold: number | null; numericThreshold: number | null; operatingHourStart: string | null; operatingHourEnd: string | null; staleDataHours: number | null; baselinePeriodDays: number | null; minimumSampleSize: number; cooldownDays: number; configuredBy: { name: string } | null; configuredAt: string };

async function requestJson(url: string, init?: RequestInit) { const response = await fetch(url, init); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? "Request failed"); return body; }

export default function AnalyticsRulesPage() {
  const [rules, setRules] = useState<Rule[]>([]);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { setRules((await requestJson("/api/analytics/rules")).rules); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to load rules."); } }, []);
  useEffect(() => { queueMicrotask(load); }, [load]);
  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-950 sm:px-6"><div className="mx-auto max-w-6xl space-y-4"><Link href="/analytics" className="text-sm font-medium text-cyan-800 hover:underline">← Executive analytics</Link><header className="rounded-xl bg-slate-950 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Tenant configuration</p><h1 className="mt-2 text-2xl font-semibold">Analytics rules</h1><p className="mt-1 text-sm text-slate-300">Every change creates a new immutable version. Historical indicators keep the threshold snapshot that produced them.</p></header>{error && <div role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-sm text-red-900">{error}</div>}{message && <div role="status" className="rounded border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-900">{message}</div>}<div className="grid gap-4 lg:grid-cols-2">{rules.map((rule) => <RuleCard key={rule.id} rule={rule} onSaved={async (text) => { setMessage(text); await load(); }} onError={setError} />)}</div>{rules.length === 0 && !error && <p role="status" className="rounded border border-slate-200 bg-white p-8 text-center text-slate-500">Loading safe defaults…</p>}</div></main>;
}

function RuleCard({ rule, onSaved, onError }: { rule: Rule; onSaved: (message: string) => Promise<void>; onError: (message: string) => void }) {
  const [form, setForm] = useState({ enabled: rule.enabled, evaluationPeriodDays: rule.evaluationPeriodDays, minimumOccurrenceCount: rule.minimumOccurrenceCount, severity: rule.severity, minimumSampleSize: rule.minimumSampleSize, cooldownDays: rule.cooldownDays, numericThreshold: rule.numericThreshold == null ? "" : String(rule.numericThreshold), percentageThreshold: rule.percentageThreshold == null ? "" : String(rule.percentageThreshold), staleDataHours: rule.staleDataHours == null ? "" : String(rule.staleDataHours), baselinePeriodDays: rule.baselinePeriodDays == null ? "" : String(rule.baselinePeriodDays), operatingHourStart: rule.operatingHourStart ?? "", operatingHourEnd: rule.operatingHourEnd ?? "" });
  const [busy, setBusy] = useState(false);
  const numberOrNull = (value: string) => value === "" ? null : Number(value);
  async function save() {
    setBusy(true); onError("");
    try {
      const body = { ...form, numericThreshold: numberOrNull(form.numericThreshold), percentageThreshold: numberOrNull(form.percentageThreshold), staleDataHours: numberOrNull(form.staleDataHours), baselinePeriodDays: numberOrNull(form.baselinePeriodDays), operatingHourStart: form.operatingHourStart || null, operatingHourEnd: form.operatingHourEnd || null };
      const result = await requestJson(`/api/analytics/rules/${rule.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      await onSaved(`${rule.label} saved as version ${result.rule.version}. Historical results were not rewritten.`);
    } catch (cause) { onError(cause instanceof Error ? cause.message : "Rule update failed."); }
    finally { setBusy(false); }
  }
  const field = (key: keyof typeof form, value: string | number | boolean) => setForm({ ...form, [key]: value });
  return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{rule.label}</h2><p className="mt-1 text-xs text-slate-500">{rule.code} · version {rule.version} · {rule.configuredBy?.name ?? "System safe default"}</p></div><label className="flex items-center gap-2 text-sm"><input aria-label={`${rule.label} enabled`} type="checkbox" checked={form.enabled} onChange={(event) => field("enabled", event.target.checked)} />Enabled</label></div><p className="mt-3 text-sm text-slate-600">{rule.description}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><NumberField label="Evaluation period days" value={form.evaluationPeriodDays} onChange={(value) => field("evaluationPeriodDays", value)} /><NumberField label="Minimum occurrence count" value={form.minimumOccurrenceCount} onChange={(value) => field("minimumOccurrenceCount", value)} /><NumberField label="Minimum sample size" value={form.minimumSampleSize} onChange={(value) => field("minimumSampleSize", value)} /><NumberField label="Cooldown days" value={form.cooldownDays} onChange={(value) => field("cooldownDays", value)} /><TextField label="Numeric threshold" type="number" value={form.numericThreshold} onChange={(value) => field("numericThreshold", value)} /><TextField label="Percentage threshold" type="number" value={form.percentageThreshold} onChange={(value) => field("percentageThreshold", value)} /><TextField label="Stale-data hours" type="number" value={form.staleDataHours} onChange={(value) => field("staleDataHours", value)} /><TextField label="Baseline period days" type="number" value={form.baselinePeriodDays} onChange={(value) => field("baselinePeriodDays", value)} /><TextField label="Operating start" type="time" value={form.operatingHourStart} onChange={(value) => field("operatingHourStart", value)} /><TextField label="Operating end" type="time" value={form.operatingHourEnd} onChange={(value) => field("operatingHourEnd", value)} /><label className="text-xs font-medium text-slate-600">Severity<select aria-label={`${rule.label} severity`} className="mt-1 w-full rounded border border-slate-300 p-2 text-sm" value={form.severity} onChange={(event) => field("severity", event.target.value)}>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((severity) => <option key={severity}>{severity}</option>)}</select></label></div><button className="mt-4 rounded bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" disabled={busy} onClick={() => void save()}>Save new rule version</button></section>;
}

function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs font-medium text-slate-600">{label}<input aria-label={label} type="number" min={0} className="mt-1 w-full rounded border border-slate-300 p-2 text-sm" value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function TextField({ label, type, value, onChange }: { label: string; type: "number" | "time"; value: string; onChange: (value: string) => void }) { return <label className="text-xs font-medium text-slate-600">{label}<input aria-label={label} type={type} className="mt-1 w-full rounded border border-slate-300 p-2 text-sm" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
